// src/main/app.svelte
<script>
  import Finder from "./finder/index.svelte";
  import Playlist from "./playlist/index.svelte";
  import Player from "./player/index.svelte";

  export let json;
  export let api;
</script>

<main>
  <Finder artists={json} />
  <Playlist />
  <Player {api} />
</main>

<style>
  main {
    position: relative;
    height: var(--mmssHeight);
    overflow: hidden;

    --mmssHeight: 100vh;
    --finderHeight: calc(var(--mmssHeight) - var(--footerHeight));
    --footerHeight: 10vh;
  }
</style>

// src/mmss/container/app.jsx
import React from 'react';
import styled from 'styled-components';

import Finder from './finder';
import Playlist from './playlist';
import Player from './player';

const MmssApp = () => (
  <Wrap>
    <Finder />
    <Playlist />
    <Player />
  </Wrap>
);

const Wrap = styled.div`
  position: relative;
  height: var(--mmssHeight);
  overflow: hidden;

  --mmssHeight: 100vh;
  --finderHeight: calc(var(--mmssHeight) - var(--footerHeight));
  --footerHeight: 10vh;
`;

// Appなのでcontainerにしたけど、inject()するものがない
export default MmssApp;
