// src/player/components/finder.svelte
<script>
  import ArtistColumn from "./artist-column.svelte";
  import AlbumColumn from "./album-column.svelte";
  import SongColumn from "./song-column.svelte";

  export let artists;
  let albums = [];
  let songs = [];

  const selected = {
    artist: "",
    album: "",
  };
  function selectArtist(artist) {
    selected.artist = artist.name;
    selected.album = "";
    albums = artist.albums;
  }
  function selectAlbum(album) {
    selected.album = album.name;
    songs = album.songs;
  }
</script>

<div class="Finder">
  <ArtistColumn {artists} selected="{selected.artist}" {selectArtist} />
  <AlbumColumn {albums} selected="{selected.album}" {selectAlbum} />
  <SongColumn {songs} />
</div>

<style>
  .Finder {
    display: grid;
    grid-template-columns: 25% 25% 50%;
    height: var(--finderHeight);
  }
</style>

// src/mmss/container/finder.jsx
import React from 'react';
import styled from 'styled-components';
import { inject } from 'mobx-react';

import ArtistColumn from '../component/finder/artist-column';
import AlbumColumn from '../component/finder/album-column';
import SongColumn from '../component/finder/song-column';

const Finder = ({ finder, ui, event }) => {
  const {
    onClickSortArtist,
    onClickArtist,
    onClickAlbum,
    onClickPlayArtist,
    onClickPlayAlbum,
    onClickPlaySong,
    onClickAddSongToPlaylist,
  } = event;

  return (
    <Wrap>
      <ArtistColumn
        ui={ui}
        artists={finder.artists}
        onClickSortArtist={onClickSortArtist}
        onClickArtist={onClickArtist}
        onClickPlayArtist={onClickPlayArtist}
      />

      <AlbumColumn
        ui={ui}
        albums={finder.albums}
        onClickAlbum={onClickAlbum}
        onClickPlayAlbum={onClickPlayAlbum}
      />

      <SongColumn
        songs={finder.songs}
        onClickPlaySong={onClickPlaySong}
        onClickAddSongToPlaylist={onClickAddSongToPlaylist}
      />
    </Wrap>
  );
};

const Wrap = styled.div`
  display: grid;
  grid-template-columns: 25% 25% 50%;
  height: var(--finderHeight);
`;

export default inject('event','finder', 'ui')(Finder);
