// src/script/mmss/component/playlist/item.jsx
import React from 'react';
import { observer } from 'mobx-react';

import Time, { format } from '../shared/time.jsx';

export const PlaylistItem = observer(({ no, item, isPlaying, onClick }) => (
  <div className="PlaylistItem">
    <div className="PlaylistItem_No">{no}</div>
    <div className="PlaylistItem_Mark">
      {isPlaying ? (
        <img src="/image/i-playing.png" />
      ) : null }
    </div>
    <div className="PlaylistItem_Name" title={item.name}>
      {isPlaying ? (
        <span>{item.name || '-'}</span>
      ) : (
        <a
          href="#"
          onClick={ev => {
            ev.preventDefault();
            onClick(item);
          }}
        >
          {item.name || '-'}
        </a>
      )}
    </div>
    <div className="PlaylistItem_Artist" title={item.artist}>
      {item.artist || '-'}
    </div>
    <div className="PlaylistItem_Album" title={item.album}>
      {item.album || '-'}
    </div>
    <div className="PlaylistItem_Duration" title={format(item.duration)}>
      <Time seconds={item.duration} />
    </div>
  </div>
));

export const PlaylistHeader = () => (
  <div className="PlaylistItem">
    <div className="PlaylistItem_No" />
    <div className="PlaylistItem_Mark" />
    <div className="PlaylistItem_Name">Song</div>
    <div className="PlaylistItem_Artist">Artist</div>
    <div className="PlaylistItem_Album">Album</div>
    <div className="PlaylistItem_Duration">Time</div>
  </div>
);

// src/main/playlist/item.svelte
<script>
  import { formatTime } from "../utils";

  export let no;
  export let item;
  export let isPlaying;
</script>

{#if item}
  <div class="Item">
    <div class="no">{no}</div>
    <div class="mark">
      {#if isPlaying}
        <img src="/image/i-playing.svg" alt="playing" />
      {/if}
    </div>
    <div class="entry" title={item.name}>
      {#if isPlaying}
        <span>{item.name}</span>
      {:else}
        <a href="/" on:click|preventDefault>{item.name}</a>
      {/if}
    </div>
    <div class="entry" title={item.artist}>{item.artist}</div>
    <div class="entry" title={item.album}>{item.album}</div>
    <div class="duration">{formatTime(item.duration)}</div>
  </div>
{:else}
  <div class="Item">
    <div class="no" />
    <div class="mark" />
    <div class="entry">Song</div>
    <div class="entry">Artist</div>
    <div class="entry">Album</div>
    <div class="duration">Time</div>
  </div>
{/if}

<style>
  .Item {
    display: grid;
    grid-template-columns: 4% 4% 40% 20% 20% 10%;
  }

  .Item .no {
    text-align: right;
  }

  .Item .mark {
    text-align: right;
    padding-right: 5px;
  }
  .Item .mark img {
    height: 8px;
  }

  .Item .entry {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .Item .duration {
    text-align: right;
  }
</style>
