// src/mmss/component/playlist/item.jsx
import React from 'react';
import { observer } from 'mobx-react';
import styled from 'styled-components';

import Time, { format } from '../shared/time';

export const PlaylistItem = observer(({ no, item, isPlaying, onClick }) => (
  <Wrap>
    <No>{no}</No>
    <Mark>
      {isPlaying ? (
        <img src="/image/i-playing.png" />
      ) : null }
    </Mark>
    <Item title={item.name}>
      {isPlaying ? (
        <span>{item.name || '-'}</span>
      ) : (
        <a
          href="#"
          onClick={ev => {
            ev.preventDefault();
            onClick(item);
          }}
        >
          {item.name || '-'}
        </a>
      )}
    </Item>
    <Item title={item.artist}>
      {item.artist || '-'}
    </Item>
    <Item title={item.album}>
      {item.album || '-'}
    </Item>
    <Duration title={format(item.duration)}>
      <Time seconds={item.duration} />
    </Duration>
  </Wrap>
));

export const PlaylistHeader = () => (
  <Wrap>
    <No />
    <Mark />
    <Item>Song</Item>
    <Item>Artist</Item>
    <Item>Album</Item>
    <Duration>Time</Duration>
  </Wrap>
);

const Wrap = styled.div`
  display: grid;
  grid-template-columns: 4% 4% 40% 20% 20% 10%;
`;

const No = styled.div`
  text-align: right;
`;

const Mark = styled.div`
  text-align: right;
  padding-right: 5px;

  & img {
    height: 8px;
  }
`;

const Item = styled.div`
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
`;

const Duration = styled.div`
  text-align: right;
`;

// src/main/playlist/item.svelte
<script>
  import { formatTime } from "../utils";

  export let no;
  export let item;
  export let isPlaying;
</script>

{#if item}
  <div class="Item">
    <div class="no">{no}</div>
    <div class="mark">
      {#if isPlaying}
        <img src="/image/i-playing.svg" alt="playing" />
      {/if}
    </div>
    <div class="entry" title={item.name}>
      {#if isPlaying}
        <span>{item.name}</span>
      {:else}
        <a href="/" on:click|preventDefault>{item.name}</a>
      {/if}
    </div>
    <div class="entry" title={item.artist}>{item.artist}</div>
    <div class="entry" title={item.album}>{item.album}</div>
    <div class="duration">{formatTime(item.duration)}</div>
  </div>
{:else}
  <div class="Item">
    <div class="no" />
    <div class="mark" />
    <div class="entry">Song</div>
    <div class="entry">Artist</div>
    <div class="entry">Album</div>
    <div class="duration">Time</div>
  </div>
{/if}

<style>
  .Item {
    display: grid;
    grid-template-columns: 4% 4% 40% 20% 20% 10%;
  }

  .Item .no {
    text-align: right;
  }

  .Item .mark {
    text-align: right;
    padding-right: 5px;
  }
  .Item .mark img {
    height: 8px;
  }

  .Item .entry {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .Item .duration {
    text-align: right;
  }
</style>
