// src/main/finder/artist-item.svelte
<script>
  export let item;
  export let isSelected;
  export let selectArtist;
</script>

<div
  class="ArtistItem"
  class:isSelected
  on:mouseenter={() => selectArtist(item)}
>
  <div>{item.name}</div>
  <div class="sub">{item.albums.length} album(s)</div>
</div>

<style>
  .ArtistItem {
    box-sizing: border-box;
    margin: 2px;
    padding: 5px 10px;
    background-color: #fff;
    cursor: pointer;
    font-size: 0.9rem;
    line-height: 1.1rem;
    border-left: 4px solid #fff;
  }

  .ArtistItem.isSelected {
    border-left: 4px solid #08f;
  }

  .ArtistItem .sub {
    padding-top: 5px;
    color: #b3b3b3;
    text-align: right;
    font-size: 0.7rem;
  }
</style>

// src/mmss/component/finder/artist-item.jsx
import React from 'react';
import { observer } from 'mobx-react';
import styled from 'styled-components';

const ArtistItem = ({
  item,
  isSelected,
  onClickPlay,
  onClick,
}) => (
  <Wrap
    className={isSelected ? 'isSelected' : ''}
    onClick={() => onClickPlay(item)}
    onMouseEnter={() => onClick(item)}
  >
    <div>{item.name || '-'}</div>
    <Sub>
      {item.albums.length} album(s)
    </Sub>
  </Wrap>
);

const Wrap = styled.div`
  box-sizing: border-box;
  margin: 2px;
  padding: 5px 10px;
  background-color: #fff;
  cursor: pointer;
  font-size: .9rem;
  line-height: 1.1rem;

  &.isSelected {
    border-left: 4px solid #08f;
  }
`;

const Sub = styled.div`
  padding-top: 5px;
  color: #b3b3b3;
  text-align: right;
  font-size: .7rem;
`;

export default observer(ArtistItem);
