// src/player/components/song-item.svelte
<script>
  import { formatTime } from "../utils";
  export let item;
</script>

<div class="SongItem">
  <div>{item.name}</div>
  <div class="sub">
    <div>{item.artist}</div>
    <div>
      Disc {item.disc || '-'} / Track {item.track || '-'} / {formatTime(item.duration)}
    </div>
  </div>
</div>

<style>
  .SongItem {
    box-sizing: border-box;
    margin: 2px;
    padding: 5px 10px;
    background-color: #fff;
    cursor: pointer;
    font-size: 0.9rem;
    line-height: 1.1rem;
  }

  .SongItem .sub {
    padding-top: 5px;
    color: #b3b3b3;
    text-align: right;
    font-size: 0.7rem;
    display: flex;
    justify-content: space-between;
  }
</style>

// src/mmss/component/finder/song-item.tsx
import React from 'react';
import { observer } from 'mobx-react';
import styled from 'styled-components';

import Time from '../shared/time';

import { Song } from '../../../shared/typings/mmss';

interface Props {
  item: Song;
  onClickPlay(item: Song): void;
  onClickAddToPlaylist(item: Song): void;
}

const SongItem = ({ item, onClickPlay, onClickAddToPlaylist }: Props) => (
  <Wrap
    onClick={ev => {
      ev.metaKey
        ? onClickAddToPlaylist(item)
        : onClickPlay(item);
    }}
  >
    <div>{item.name}</div>
    <Sub>
      <div>{item.artist}</div>
      <div>
        Disc {item.disc || '-'}
        {' / '}
        Track {item.track || '-'}
        {' / '}
        <Time seconds={item.duration} />
      </div>
    </Sub>
  </Wrap>
);

const Wrap = styled.div`
  box-sizing: border-box;
  margin: 2px;
  padding: 5px 10px;
  background-color: #fff;
  cursor: pointer;
  font-size: .9rem;
  line-height: 1.1rem;
`;

const Sub = styled.div`
  padding-top: 5px;
  color: #b3b3b3;
  text-align: right;
  font-size: .7rem;
  // Songだけ
  display: flex;
  justify-content: space-between;
`;

export default observer(SongItem);
