// src/mmss/app.jsx
import React from 'react';
import { inject, observer } from 'mobx-react';
import styled from 'styled-components';

import Finder from './container/finder';
import Playlist from './container/playlist';
import Player from './container/player';

const MmssApp = ({ store }) => {
  const { playlist, finder, ui, media } = store;

  return (
    <Wrap>
      <Finder
        {...{
          finder,
          ui,
        }}
      />
      <Playlist
        {...{
          playlist,
          ui,
        }}
      />
      <Player
        {...{
          playlist,
          media,
          ui,
        }}
      />
    </Wrap>
  );
};

const Wrap = styled.div`
  position: relative;
  height: var(--mmssHeight);
  overflow: hidden;

  --mmssHeight: 100vh;
  --finderHeight: calc(var(--mmssHeight) - var(--footerHeight));
  --footerHeight: 10vh;
`;

export default inject('event')(observer(MmssApp));

// src/player/App.svelte
<script>
  import Finder from "./components/Finder.svelte";
  import Playlist from "./components/Playlist.svelte";
  import Player from "./components/Player.svelte";

  export let json;
  export let api;
</script>

<main>
  <Finder artists="{json}" />
  <Playlist />
  <Player {api} />
</main>

<style>
  main {
    position: relative;
    height: var(--mmssHeight);
    overflow: hidden;

    --mmssHeight: 100vh;
    --finderHeight: calc(var(--mmssHeight) - var(--footerHeight));
    --footerHeight: 10vh;
  }
</style>
