// src/main/player/audio.svelte
<script>
  export let src;

  let el;
  // Use Space key to toggle pause/play
  function handleKeydown(ev) {
    if (ev.keyCode !== 32) return;
    if (el instanceof HTMLAudioElement === false) return;
    if (el.readyState !== HTMLAudioElement.HAVE_ENOUGH_DATA) return;

    ev.preventDefault();
    el.paused ? el.play() : el.pause();
  }
</script>

<audio
  class="Audio"
  autoplay
  controls
  controlsList="nodownload"
  {src}
  on:ended
  bind:this={el}
/>
<svelte:window on:keydown={handleKeydown} />

<style>
  .Audio {
    width: 100%;
    vertical-align: top;
  }
</style>

// src/mmss/component/player/audio.tsx
import React from 'react';
import { observer } from 'mobx-react';
import styled from 'styled-components';

interface Props {
  src: string;
  onEnded(): void;
}

class Audio extends React.Component<Props> {
  elRef: React.RefObject<HTMLAudioElement>;

  constructor(props: Props) {
    super(props);

    this.elRef = React.createRef();
    this.handleKeyDown = this.handleKeyDown.bind(this);
  }

  render() {
    const { src, onEnded } = this.props;

    return (
      <Wrap>
        <audio
          ref={this.elRef}
          autoPlay
          controls
          controlsList="nodownload"
          src={src}
          onEnded={onEnded}
        />
      </Wrap>
    );
  }

  componentDidMount() {
    window.addEventListener('keydown', this.handleKeyDown, false);
  }

  componentWillUnmount() {
    window.removeEventListener('keydown', this.handleKeyDown, false);
  }

  private handleKeyDown(ev: KeyboardEvent) {
    if (ev.keyCode !== 32) {
      return;
    }

    const el = this.elRef.current;
    if (!el || el instanceof HTMLAudioElement === false) {
      return;
    }
    if (el.readyState !== HTMLAudioElement.prototype.HAVE_ENOUGH_DATA) {
      return;
    }

    ev.preventDefault();
    el.paused ? el.play() : el.pause();
  }
}

const Wrap = styled.audio`
  width: 100%;
  vertical-align: top;
`;

export default observer(Audio);
