// src/main/player/progress-bar.svelte
<script>
  export let progress = 0;

  $: width = `${progress}%`;
  $: opacity = progress === 0 ? 0 : 1;
</script>

<div class="ProgressBar">
  <div class="inner" style="width: {width}; opacity: {opacity}" />
</div>

<style>
  .ProgressBar {
    height: 4px;
    background-color: #e6e6e6;
  }

  .ProgressBar .inner {
    height: 100%;
    background-color: var(--linkColor);
    will-change: width;
    transition: width 0.2s ease;
  }
</style>

// src/mmss/component/player/progress-bar.jsx
import React from 'react';
import { observer } from 'mobx-react';
import styled from 'styled-components';

const ProgressBar = ({ loadProgress }) => (
  <Wrap>
    <Inner style={{ width: `${loadProgress}%` }} />
  </Wrap>
);

const Wrap = styled.div`
  height: 4px;
  background-color: #e6e6e6;
`;

const Inner = styled.div`
  height: 4px;
  background-color: var(--linkColor);
`;

export default observer(ProgressBar);
