// src/mmss/component/finder/album-column.jsx
import React from 'react';
import { observer } from 'mobx-react';
import styled from 'styled-components';

import AlbumItem from './album-item';

const AlbumColumn = ({ ui, albums, onClickAlbum, onClickPlayAlbum }) => (
  <Wrap>
    <Head>
      <p>Albums</p>
    </Head>
    <Body>
      <ul>
        {albums.map(album => (
          <li key={album.name}>
            <AlbumItem
              item={album}
              isSelected={album.name === ui.selected.album}
              onClick={onClickAlbum}
              onClickPlay={onClickPlayAlbum}
            />
          </li>
        ))}
      </ul>
    </Body>
  </Wrap>
);

const Wrap = styled.div`
  display: grid;
  grid-template-rows: 30px 1fr;
  height: inherit;
`;

const Head = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 10px;
  height: 30px;
  background-color: #9cc2c3;
  color: #fff;
  text-transform: uppercase;
  font-size: .8rem;
`;

const Body = styled.div`
  overflow: scroll;
`;

export default observer(AlbumColumn);

// src/main/finder/album-column.svelte
<script>
  import AlbumItem from "./album-item.svelte";

  export let albums;
  export let selected;
  export let selectAlbum;
</script>

<div class="AlbumColumn">
  <div class="head">
    <p>Albums</p>
  </div>
  <div class="body">
    <ul>
      {#each albums as album (album)}
        <li>
          <AlbumItem
            item={album}
            isSelected={selected === album.name}
            {selectAlbum}
          />
        </li>
      {/each}
    </ul>
  </div>
</div>

<style>
  .AlbumColumn {
    display: grid;
    grid-template-rows: 30px 1fr;
    height: inherit;
  }

  .AlbumColumn .head {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 0 10px;
    height: 30px;
    background-color: #9cc2c3;
    color: #fff;
    text-transform: uppercase;
    font-size: 0.8rem;
  }

  .AlbumColumn .body {
    overflow: scroll;
  }
</style>
