// src/script/mmss/component/finder/artist-column.jsx
import React from 'react';
import { observer } from 'mobx-react';
import styled from 'styled-components';

import ArtistItem from './artist-item.jsx';

const ArtistColumn = ({
  ui,
  artists,
  onClickSortArtist,
  onClickArtist,
  onClickPlayArtist,
}) => (
  <Wrap>
    <Head>
      <p>Artists</p>
      <Sorter onClick={() => onClickSortArtist()}>
        {ui.sortBy}
        <img src="/image/i-sort.png" />
      </Sorter>
    </Head>

    <Body>
      <ul>
        {artists
          // 絞込されてるならそれ、されてないなら全部
          .filter(artist => (ui.filterBy ? artist.name === ui.filterBy : true))
          .map(artist => (
            <li key={artist.name}>
              <ArtistItem
                item={artist}
                isSelected={artist.name === ui.selected.artist}
                onClick={onClickArtist}
                onClickPlay={onClickPlayArtist}
              />
            </li>
          ))}
      </ul>
    </Body>
  </Wrap>
);

const Wrap = styled.div`
  display: grid;
  grid-template-rows: 30px 1fr;
  height: inherit;
`;

const Head = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 10px;
  height: 30px;
  background-color: #9cc2c3;
  color: #fff;
  text-transform: uppercase;
  font-size: .8rem;
`;

const Sorter = styled.a`
  font-size: .6rem;
  color: inherit;

  & img {
    height: 10px;
    vertical-align: text-top;
    margin-left: 5px;
  }
`;

const Body = styled.div`
  overflow: scroll;
`;

export default observer(ArtistColumn);

// src/main/finder/artist-column.svelte
<script>
  import ArtistItem from "./artist-item.svelte";

  export let artists;
  export let selected;
  export let selectArtist;
</script>

<div class="ArtistColumn">
  <div class="head">
    <p>Artists</p>
    <div class="controller">
      TODO
      <img src="/image/i-sort.svg" alt="sort" />
    </div>
  </div>
  <div class="body">
    <ul>
      {#each artists as artist (artist)}
        <li>
          <ArtistItem
            item={artist}
            isSelected={selected === artist.name}
            {selectArtist}
          />
        </li>
      {/each}
    </ul>
  </div>
</div>

<style>
  .ArtistColumn {
    display: grid;
    grid-template-rows: 30px 1fr;
    height: inherit;
  }

  .ArtistColumn .head {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 0 10px;
    height: 30px;
    background-color: #9cc2c3;
    color: #fff;
    text-transform: uppercase;
    font-size: 0.8rem;
  }

  .ArtistColumn .controller {
    display: flex;
    align-items: center;
    font-size: 0.6rem;
    cursor: pointer;
  }

  .ArtistColumn .controller img {
    height: 12px;
    vertical-align: text-top;
    margin: 0 5px;
  }

  .ArtistColumn .body {
    overflow: scroll;
  }
</style>
